id: P87D4B163
initial_creation_type: input
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: en
  volumes:
    0dceca231f7e446e875653c598a4ab08:
      title: .txt
      base_file: .txt.txt
      work_id: W648FFF40
  chapter_to_tile: {}
created_at: '2022-03-01T21:21:15.248776'
last_modified_at: '2022-03-01T21:21:15.248782'
